# Generated by Django 5.0.7 on 2024-08-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0002_citizenship'),
    ]

    operations = [
        migrations.CreateModel(
            name='children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vs.person')),
            ],
        ),
    ]
